### ISSUE TITLE
Maintainer status?

### ISSUE THREAD

**Issue by davidparsson** [python-injector/injector#211]
Hi!

I work at @amramedical, together with @tobni and @erikced who also has contributed here, and at @amramedical we rely heavily on Injector. I'm just reaching out to see what the status and future is with regards to maintenance of this package. We've been very happy with the timely responses and resolutions in the past, but we have noticed a slight decline. And we would like to help!

Would you be interested in letting a few of us help maintaining? Or would you even be interested in letting this go entirely? My employer @amramedical is willing to formally step in and take ownership, or provide assistance.

**Comment by jstasiak** [comment]
Hey @davidparsson, thank you for your past contributions and for this offer to help.

The status is I spend some time on the project every now and then when I see something important to do, I just haven't seen anything pressing recently (or I missed it). The library is rather stable these days so there isn't much to do.

That said, there definitely are some outstanding low priority (for me) issues that could use resolving etc. I just gave you write access to the repository and any help is welcome.

I do have some views about how I see the library developed and progressing so let's make sure we're on the same page in case you want to change something big-ish or possibly controversial, but other than that use your best judgment.

Thank you once again.

**Comment by davidparsson** [comment]
That sounds very reasonable. I agree that this is a stable and well working library, I’ll just try to help and future-proof this. Thanks a lot!
