### ISSUE TITLE
Testing example in docs is not working. ImportError: cannot import name 'with_injector' from 'injector'

### ISSUE THREAD

**Issue by pavlomorozov** [python-injector/injector#220]
The problem is described at https://github.com/python-injector/injector/issues/146 and issue is closed. However, the manual still not updated: https://github.com/python-injector/injector/blob/master/docs/testing.rst

**Comment by davidparsson** [comment]
Thanks for reporting! Pull requests are welcome.

**Comment by pavlomorozov** [comment]
@davidparsson any update on this?

**Comment by davidparsson** [comment]
Sorry, nope, but thanks for the reminder.

You're right you can't push here, but you can [create your own fork and then open a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). That's obviously a bit more work for you, but will likely get this resolved faster. Thanks and good luck!

**Comment by pavlomorozov** [comment]
I made a PR https://github.com/python-injector/injector/pull/236. Does it look fine?

**Comment by davidparsson** [comment]
It does. Thanks!
