### ISSUE TITLE
Issue with ClassAssistedBuilder

### ISSUE THREAD

**Issue by taiharry108** [python-injector/injector#238]
This is my first time creating any issue on github, so please let me know if I am missing anything!
I started learning this amazin library and everything made sense until `Assisted Injection`
I was trying out the example in the docs and it just didn't work. Here's my code:
```
from injector import ClassAssistedBuilder
class Database: pass

class User:
    def __init__(self, name):
        self.name = name


class UserUpdater:
    def __init__(self, db: Database, user):
        pass


injector = Injector()
builder = injector.get(ClassAssistedBuilder[UserUpdater])
user = User('John')
user_updater = builder.build(user=user)
```

It threw me this error:
`injector.CallError: Call to UserUpdater.__init__(user=<__main__.User object at 0x7f8ea0bffe50>) failed: UserUpdater.__init__() missing 1 required positional argument: 'db' (injection stack: [])`
It would work, however if I put a `Database` object in the `build` method like this
`user_updater = builder.build(user=user, db=injector.get(Database))`

So here's my confusion,

1. Is the doc wrong for this section?
2. I thought `db` would be injected by the injector automatically, but apparently it's not the case and if it doesn't, doesn't it require a lot more code?

**Comment by jstasiak** [comment]
Hey @taiharry108, thank you for the report. What Injector and Python versions?

**Comment by taiharry108** [comment]
@jstasiak
`injector==0.21.0`
`python==3.11.5`

**Comment by davidparsson** [comment]
Does it work better if you add an `@inject` decorator to the constructor of `UserUpdater`?

**Comment by taiharry108** [comment]
@davidparsson it works!
